### ISSUE TITLE
Userdata was missing 

### ISSUE THREAD

**Issue by nexnic** [nexnic/JS2#11]
variable.mjs:24 Uncaught ReferenceError: userData is not defined
    at variable.mjs:24:30
    
    Need to fix this

**Comment by nexnic** [comment]
This most be an empty value need get for adding when we are using it

**Comment by nexnic** [comment]
See on body userData is value but have now value because is not defined. let's test `${Userdata}`; 

postData: {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
        },
        body: JSON.stringify(userData),
    },

**Comment by nexnic** [comment]
Let's test make this empty value and we need new fix on it

**Comment by nexnic** [comment]
Same on token 

Uncaught ReferenceError: token is not defined
    at variable.mjs:30:38
(anonymous) @ variable.mjs:30

**Comment by nexnic** [comment]
fix Remove for now need to fix this later or check. {postData: {…}, fetchData: {…}}
fetchData
: 
{method: 'GET', headers: {…}}
postData
: 
{method: 'POST', headers: {…}, body: undefined}
[[Prototype]]
: 
Object

**Comment by nexnic** [comment]
Close this bug for now
