### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'innerHTML') 

### ISSUE THREAD

**Issue by nexnic** [nexnic/JS2#21]
New Bug 

at post.mjs:18:13
at Array.forEach (<anonymous>)
at ShowFeed (post.mjs:15:16)
at feedPost (main.mjs:24:5)
at main.mjs:27:1

**Comment by nexnic** [comment]
Adding new section on main.html 
id="feed"

new bug Uncaught SyntaxError: The requested module '../base/domcontroller.mjs' does not provide an export named 'NewsFeed' (at post.mjs:2:9)

**Comment by nexnic** [comment]
Fix new bug 

new bug post.mjs 18 only new name

**Comment by nexnic** [comment]
Now it's work
